local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/turtle"))()

local OwO = library:Window("Table Turtle Hub")

OwO:Toggle("1", true, function(bool)
    print(bool)
end)
OwO:Toggle("2", true, function(bool)
    print(bool)
end)
OwO:Toggle("3", true, function(bool)
    print(bool)
end)
OwO:Toggle("4", true, function(bool)
    print(bool)
end)
OwO:Toggle("5", true, function(bool)
    print(bool)
end)
OwO:Toggle("6", true, function(bool)
    print(bool)
end)
